# Generated by Django 6.0.3 on 2026-03-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='media/event_images/default.jpeg', upload_to='media/event_images/'),
        ),
    ]
